### ISSUE TITLE
Documentation: What should the image filenames be?

### ISSUE THREAD

**Issue by tswast** [mutantstandard/forc#1]
I’m using PNG images for my font, since it’s pixel art, so forc seems a more relevant choice for me to use than orxporter. In order to determine what filenames I should use, I reviewed the documentation at https://github.com/mutantstandard/forc/blob/master/docs/howto/input.md

I understand the folder names instructions, but I don’t know what the filenames should be. Based on https://github.com/mutantstandard/forc/blob/master/docs/howto/aliases.md I’m guessing they should be hex unicode codepoints, with dashes acting as ZWJ?

Thanks for writing as much documentation as you have already!

**Comment by dzuk-mutant** [comment]
You've gotta make it 1 or more hex codepoints (without U+ or 0x at the beginning), with a delimiter in between them if you're doing more than one. The default delimiter is a dash '-', but you can set it to something else in the build flags with `-d`. The dashes don't act as ZWJ, just a delimiter between multiple points in a sequence/ligature; you have to add ZWJ codepoints manually (since a lot of valid codepoint sequences/ligatures don't actually involve ZWJ).

(I'll add a todo note in the future to remind me to make this clearer in the future! Thanks for asking!)

**Comment by dzuk-mutant** [comment]
Some examples from Mutant Standard's font build files:

```
png-32
    1f3a5.png
    1f5ef-fe0f.png
    1f446-fe0f-101650-101604.png
    1f3f3-200d-1f308.png (200d = ZWJ)
    ...
png-128
    etc.
etc.
```

**Comment by dzuk-mutant** [comment]
Okay, I've gone over the docs and clarified how filenames work. (You also might be interested in knowing that I've also fixed a bunch of errors, completed the manifest documentation and provided an example/template manifest file :) )

**Comment by tswast** [comment]
Hooray! Thank you. I'm excited to give this a try.
